config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :purchases
  resources :users

  root 'purchases#index'
  get "*path", to: redirect('/')
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.role == 'manager'
      can :manage, :all
    else
      # can [:read, :update, :destroy], Car
      can [:read, :create], Purchase
      can :read, User
      
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
 
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  is_impressionable
  enum status: { requested: 0, processing: 1, cancelled: 2 , closed: 3  }
  scope :search,->(term){ where("buyer_name like ?", "#{term}%")}

  has_many :notes, dependent: :destroy


  accepts_nested_attributes_for :notes, reject_if: :all_blank, allow_destroy: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { manager: 0, employee: 1 }

  has_one :purchase

  scope :search,->(term){ where("name like ?", "#{term}%")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


    before_action :conf_permitted_parameter, if: :devise_controller?

    def conf_permitted_parameter
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        
    end

    
    
end

app/controllers/notes_controller00.rb
class NotesController < SistemaController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :note, :purchase_id)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < SistemaController
  before_action :set_purchase, only: %i[ show edit update destroy ]
  # impressionist actions: :show

  # GET /purchases or /purchases.json
  def index
    # @purchases = Purchase.all
    if current_user.role == 'manager'
       @purchases = Purchase.search(params[:search])
    else
       @purchases = Purchase.search(params[:search]).where(user_id: current_user.id)
    end
  end

  # GET /purchases/1 or /purchases/1.json
  def show
    impressionist(@purchase)
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user_id = current_user.id
   
   
    

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: "Purchase was successfully created." }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: "Purchase was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: "Purchase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_params
      params.require(:purchase).permit(:buyer_name, :email, :status, :user_id,
        notes_attributes:[:id, :name, :note , :purchase_id, :_destroy]
      )
    end
end

app/controllers/sistema_controller.rb
class SistemaController < ApplicationController
    layout "admin"
    before_action :authenticate_user!


    load_and_authorize_resource

    rescue_from CanCan::AccessDenied do |exception|
        redirect_to '/', :alert => exception.message
    end
end

app/controllers/users_controller.rb
class UsersController < SistemaController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.search(params[:search])
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|

      if password_blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end

      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :role, :email, :password)
    end

    def password_blank?
      params[:user][:password].blank? &&
      params[:user][:password_confirmation].blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaBr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body >
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="/ruby.png" style="width: 40px;" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Purchases", purchases_path , class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "User", users_path , class:"nav-link"%>
        </li>
       
      </ul>
      <div class="form-inline my-2 my-lg-0">
       <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name%>     
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           
          
            <%= link_to  destroy_user_session_path,class:"dropdown-item" ,method: :delete do %>
                    <i class="fa fa-sign-out fa-fw"></i> Logout
            <% end %>
          </div>
        </li>
        <li>
        </li>
       
      </ul>
       </div>
    </div>
  </nav>

</div>
   

<div class="container">

  <%= yield %>
</div>
  
  </body>
</html>

app/views/layouts/application.html.erb
 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Log in</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/template/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="/template/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/template/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
  <body >
   
   

      <%= yield %>
  

      <script src="/template/plugins/jquery/jquery.min.js"></script>
      <!-- Bootstrap 4 -->
      <script src="/template/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
      <!-- AdminLTE App -->
      <script src="/template/dist/js/adminlte.min.js"></script>
   </body>
</html>
      

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :buyer_name , class: 'form-label' %>
    <%= form.text_field :buyer_name , class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email, class: 'form-label'  %>
    <%= form.text_field :email,  class: 'form-control'  %>
  </div>

 

  <div class="field">
    <%= form.label :status,  class: 'form-label' %>
    <%= form.select :status, Purchase.statuses.keys, {}, {class: "form-control"} %>
  </div>

 
    <h2> Notes #</h2>
    <div id="notes">
      
      <%= form.fields_for :notes do |note_fields| %>
         <%= render partial: "note_fields", locals:{ f: note_fields }%>
      <%end%>
      <br>
          <%=link_to_add_association('+ Add Notes',form, :notes ,class: "btn btn-info", style: 'color: white',  remote: true)%>
  </div>
      <br>
                         
  


  <div class="actions">
    <!-- <%= form.submit %> -->
    <button type="submit" class="btn btn-success">Guardar</button>
  </div>
<% end %>

app/views/purchases/_note_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :note, class: "form-label" %>
        <%= f.text_area :note, class: "form-control" %>
    </div>
   <%= link_to_remove_association f, class: 'btn btn-danger btn-sm ' do %>
    Remove Note
    <% end %>
</div>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase, class: 'btn btn-primary',  style: 'color: white' %> |
<%= link_to 'Back', purchases_path, class: 'btn btn-primary',  style: 'color: white' %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

    <%=form_tag purchases_path , method: :get do%>
           
      <div class="input-group input-group" style="width: 300px; padding-button:5px;">
        <%= text_field_tag(:search, params[:search], :class => "form-control" , placeholder: "Search" ) %>
        
        <div class="input-group-btn"  style=" padding-button:5px;">
            <%= submit_tag("buscar",class:"btn btn-primary " ) do %>  
            <% end %>
        </div>
      </div>
    <% end %>

<table class="table">
  <thead>
    <tr>
      <th>Buyer name</th>
      <th>Email</th>
      <th>Status</th>
      <th>User</th>
      <th>Views</th>
      <th colspan="3"></th>
      <th>Update</th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.buyer_name %></td>
        <td><%= purchase.email %></td>
        <td><%= purchase.status %></td>
        <td><%= purchase.user.name %></td>
        <td><%= purchase.impressionist_count %></td>

        <% if can? :show, Purchase %> 
        <td><%= link_to 'Show', purchase , class: 'btn btn-success', style:'color: white'%></td>
        <% end %>
        <% if can? :edit, Purchase %> 
        <td><%= link_to 'Edit', edit_purchase_path(purchase) , class: 'btn btn-warning', style:'color: white'%></td>
         <% end %>
        <% if can? :destroy, Purchase %> 
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger', style:'color: white' %></td>
          <% end %>
       
        <td><%= purchase.updated_at.strftime('%d/%m/%Y - %H:%M  ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<% if can? :create, Purchase %>
  <%= link_to 'New Purchase', new_purchase_path, class: 'btn btn-success', style:'color: white' %>
<% end %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Back', purchases_path, class: 'btn btn-danger', style: 'color: white' %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buyer name:</strong>
  <%= @purchase.buyer_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @purchase.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @purchase.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @purchase.user.name %>
</p>

<div class="my-3 p-3 bg-body rounded shadow-sm" style="width: 600px;">
    <h6 class="border-bottom pb-2 mb-0">Recent Notes</h6>

    <% @purchase.notes.each do |note| %>
       
    <div class="d-flex text-muted pt-3">

      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark p-1">  #  <%= note.name%></strong>
          <%= note.note%>
      </p>
    </div>
    <% end %>
    
   
  </div>



<%= link_to 'Edit', edit_purchase_path(@purchase), class: 'btn btn-primary', style:'color: white' %> |
<%= link_to 'Back', purchases_path , class: 'btn btn-primary', style:'color: white'%>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name , class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>


  <div class="field">
    <%= form.label :role, class: 'form-label' %>
    <%= form.select :role, User.roles.keys, {},class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :password , class: 'form-label'%>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-success">Guardar</button>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class: 'btn btn-primary', style:'color: white' %> |
<%= link_to 'Back', users_path, class: 'btn btn-primary', style:'color: white' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%=form_tag users_path , method: :get do%>
           
      <div class="input-group input-group" style="width: 300px; padding-button:5px;">
        <%= text_field_tag(:search, params[:search], :class => "form-control" , placeholder: "Search" ) %>
        
        <div class="input-group-btn"  style=" padding-button:5px;">
            <%= submit_tag("buscar",class:"btn btn-primary " ) do %>  
            <% end %>
        </div>
      </div>
<% end %>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th> 
      <% if can? :edit, User %> 
      <th colspan="3"></th>
       <% end %>
      <th>Update</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= user.email %></td>
     
        <% if can? :edit, User %> 
        <td><%= link_to 'Show', user, class: 'btn btn-success', style:'color: white' %></td>
          <% end %>
        <% if can? :edit, User %> 
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning', style:'color: white' %></td>
          <% end %>
        <% if can? :edit, User %> 
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style:'color: white' %></td>
         <% end %>
       
         <td><%= user.updated_at.strftime('%d/%m/%Y - %H:%M  ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if can? :create, User %>
  <%= link_to 'New User', new_user_path, class: 'btn btn-success', style:'color: white' %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) , class: 'btn btn-primary', style:'color: white'%> |
<%= link_to 'Back', users_path , class: 'btn btn-primary', style:'color: white' %>